<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CEA.Application\CEA.Application.csproj" />
    <ProjectReference Include="..\CEA.Infrastructure\CEA.Infrastructure.csproj" />
    <ProjectReference Include="..\CEA.Persistence\CEA.Persistence.csproj" />
  </ItemGroup>

</Project>
