<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Docs.v1" Version="1.68.0.3498" />
    <PackageReference Include="Google.Apis.Drive.v3" Version="1.69.0.3674" />
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.30" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CEA.Application\CEA.Application.csproj" />
    <ProjectReference Include="..\CEA.Domain\CEA.Domain.csproj" />
  </ItemGroup>

</Project>
